name: Upload Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for Trusted Publishing
  contents: read

jobs:
  publish-to-pypi:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: pypi  # Match this with what you configured in PyPI

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
